language: node_js
node_js:
- stable
before_script:
- npm i
- npm run static
deploy:
  local_dir: public
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: Vw4uwBCTja9z1duoXsb/MI+P8vUEI4Ww+DG8bSmTIdlJ91CUYUsVVHlP47xfVY0XYjLiM1v/QX1twDy53QQACjOEGoVwC+WGGZ73TPCVXaR2UWH+JUGGz4zaFX8MixwoW2avNkvLi8PTMldUG3pBrlZ/j5Bo4LepRAuIHiBnTzepkOyO+CZwCKNjrEbuePoduPd+ZRxAQHnUQ0l05QaP4K3XcnjxP6ZkFMZ7iXEp0J8YxgCnU1jDTsu2FrmCwnZpRwiMRuZmD7TzAy6gzhucBtHQ++ne7CsE7KHGtq4PV4XTKWqNeeItr/8p/qF4h+5vcfNPToeKh8+c1g/kjFN3WRJoi7Srjvehc1q/SrfbJIobbpdgHqtNKZY3DqZ1TEA+ERamnQb0Bq8MFpT5xXNSW3QLFJa8mkc1mMANmrZ4vstd0/GUsvXn5oCFhZ967hLfE/OYc9lM0Y1zhMzhnTjv0zcAhqeEtJJcUmHVcCzTKruxSJQqkGheraLXhastSNlZw5RgmTaZf3HsnoQY84fMGKfudb8H8tj4TrD4gwqhz8GLex/LxlsqC1Zlo3XcGQFaeM/KY0EKZsJsO24DrRJiWUA+DM3cbSgLgZkzKgC6cJ1erh26noXrxo8Yov2Yy45g4yhAa9+EvG1ECTxDlqzpZCinMXSoTqGCmLA2WC1LyqE=
